# Azure Pipelines CI job template

parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      py27:
        conda.py: 2.7
      py35:
        conda.py: 3.5
      py36:
        conda.py: 3.6
      py37:
        conda.py: 3.7
  steps:
  - script: |
      export PATH="$CONDA/bin:$PATH"
      sudo conda install --yes conda-build
      conda build .
    displayName: 'Build'
