#
# Parallel build
#
jobs:
- job: CI
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      py27:
        conda.py: 2.7
      py35:
        conda.py: 3.5
      py36:
        conda.py: 3.6
      py37:
        conda.py: 3.7
  steps:
  - task: CondaEnvironment@1
    inputs:
      createCustomEnvironment: False
      updateConda: False
  - script: |
      sudo conda install --yes conda-build
      echo ================================
      env
      echo ================================
      conda build .
    displayName: 'Build'
