# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
# Conda Environment
# Create and activate a Conda environment.
- task: CondaEnvironment@1
  inputs:
    createCustomEnvironment: False
    #environmentName: # Required when createCustomEnvironment == True
    #packageSpecs: 'python=3' # Optional
    #updateConda: # Optional
    #installOptions: # Optional
    #createOptions: # Optional
    #cleanEnvironment: # Optional

- script: conda -y install conda-build
  displayName: 'Install conda-build'

- script: |
    echo Running the build
    echo PATH=$PATH
    conda build .
  displayName: 'Build'
