#
# Parallel build
#
jobs:
- template: azure-tpl-jobs.yml
  parameters:
    name: Linux
    vmImage: 'Ubuntu 16.04'
- template: azure-tpl-jobs.yml
  parameters:
    name: MacOS
    vmImage: 'macOS-10.13'
