#
# Based on meta.yaml found in https://anaconda.org/wwarner/pyslalib/files
#
package:
    name: pyslalib
    version: "1.0.3"

source:
    git_url: https://github.com/scottransom/pyslalib
    # no official tagged release available at time of recipe creation.
    #    rev here is latest revision at time of recipe creation.
    git_rev: "fcb0650a140a8002cc6c0e8918c3e4c6fe3f8e01"

requirements:
    build:
        - {{ compiler('fortran') }}
    host:
        - numpy
        - python
    run:
        - numpy
        - python

test:
    requires:
        - numpy
        - python
    source_files:
        - test/test_slalib.py
    commands:
        - python test/test_slalib.py
  
about:
    summary: f2py wrappers of P.T. Wallace's SLALIB positional astronomy library
    license: GPL
 
